[2024-07-03T22:03:29.397+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-03T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-07-03T23:02:36.848+0000] {scheduler_job_runner.py:1737} ERROR - Detected zombie job: {'full_filepath': '/opt/airflow/dags/my_dag.py', 'processor_subdir': '/opt/airflow/dags', 'msg': "{'DAG Id': 'exchange_rate_dag', 'Task Id': 'run_script', 'Run Id': 'scheduled__2024-02-03T00:00:00+00:00', 'Hostname': '0b7358cba041', 'External Executor Id': 'b150e1a5-d661-4fda-b0c9-53dc79fd8f65'}", 'simple_task_instance': <airflow.models.taskinstance.SimpleTaskInstance object at 0x7f48e9abc380>, 'is_failure_callback': True} (See https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#zombie-undead-tasks)
[2024-07-03T23:02:49.911+0000] {scheduler_job_runner.py:1737} ERROR - Detected zombie job: {'full_filepath': '/opt/airflow/dags/my_dag.py', 'processor_subdir': '/opt/airflow/dags', 'msg': "{'DAG Id': 'exchange_rate_dag', 'Task Id': 'run_script', 'Run Id': 'scheduled__2024-02-03T00:00:00+00:00', 'Hostname': '0b7358cba041', 'External Executor Id': 'b150e1a5-d661-4fda-b0c9-53dc79fd8f65'}", 'simple_task_instance': <airflow.models.taskinstance.SimpleTaskInstance object at 0x7f48e99733e0>, 'is_failure_callback': True} (See https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#zombie-undead-tasks)
