[2024-07-03T22:06:24.181+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T22:06:24.237+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-07-03T22:06:24.250+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-07-03T22:06:24.266+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T22:06:24.409+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-03-08 00:00:00+00:00
[2024-07-03T22:06:24.485+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T22:06:24.500+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp0uvz97aw']
[2024-07-03T22:06:24.503+0000] {standard_task_runner.py:63} INFO - Started process 193 to run task
[2024-07-03T22:06:24.528+0000] {standard_task_runner.py:91} INFO - Job 113: Subtask run_script
[2024-07-03T22:06:24.817+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-03-08T00:00:00+00:00 [running]> on host bab0a72648e8
[2024-07-03T22:06:25.745+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2024-07-03T22:06:25.747+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T22:06:25.749+0000] {logging_mixin.py:188} INFO - All credentials are set properly.
[2024-07-03T22:06:25.750+0000] {logging_mixin.py:188} INFO - Error al crear la tabla en Redshift: invalid literal for int() with base 10: 'None'
[2024-07-03T22:06:27.255+0000] {logging_mixin.py:188} INFO - Error al realizar la solicitud a la API: 401 Client Error: Unauthorized for url: https://api.apilayer.com/exchangerates_data/latest?symbols=EUR,USD,CNY&base=ARS
[2024-07-03T22:06:27.258+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-03T22:06:27.259+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T22:06:27.272+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20240703T220624, end_date=20240703T220627
[2024-07-03T22:06:27.538+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-03T22:06:27.569+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T22:06:27.671+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T23:03:52.774+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T23:03:53.795+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-07-03T23:03:53.953+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-07-03T23:03:53.960+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T23:03:54.187+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-03-08 00:00:00+00:00
[2024-07-03T23:03:54.990+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=294) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T23:03:54.940+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpcc3c0uu4']
[2024-07-03T23:03:55.475+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask run_script
[2024-07-03T23:03:55.474+0000] {standard_task_runner.py:63} INFO - Started process 317 to run task
[2024-07-03T23:03:58.996+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-03-08T00:00:00+00:00 [running]> on host 0b7358cba041
[2024-07-03T23:04:04.470+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2024-07-03T23:04:04.506+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T23:04:04.520+0000] {logging_mixin.py:188} INFO - All credentials are set properly.
[2024-07-03T23:04:04.537+0000] {logging_mixin.py:188} INFO - Error al crear la tabla en Redshift: invalid literal for int() with base 10: 'None'
[2024-07-03T23:04:07.049+0000] {logging_mixin.py:188} INFO - Error al realizar la solicitud a la API: 401 Client Error: Unauthorized for url: https://api.apilayer.com/exchangerates_data/latest?symbols=EUR,USD,CNY&base=ARS
[2024-07-03T23:04:07.100+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-03T23:04:07.120+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T23:04:07.277+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20240703T230353, end_date=20240703T230407
[2024-07-03T23:04:07.629+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-03T23:04:07.770+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T23:04:07.797+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-04T01:39:43.634+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T01:39:43.815+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-07-04T01:39:43.858+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2024-07-04T01:39:43.864+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-04T01:39:44.378+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-03-08 00:00:00+00:00
[2024-07-04T01:39:44.462+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=422) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-04T01:39:44.500+0000] {standard_task_runner.py:63} INFO - Started process 447 to run task
[2024-07-04T01:39:44.610+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmppao66s8w']
[2024-07-04T01:39:44.626+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask run_script
[2024-07-04T01:39:45.015+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-03-08T00:00:00+00:00 [running]> on host e26a552f405a
[2024-07-04T01:40:22.513+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 38 for task run_script ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 447)
[2024-07-04T01:40:25.569+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T01:40:25.606+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-04T01:40:25.610+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
