[2024-07-03T23:17:57.084+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T23:17:57.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-07-03T23:17:57.410+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-07-03T23:17:57.413+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T23:17:57.527+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-04-28 00:00:00+00:00
[2024-07-03T23:17:57.630+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-04-28T00:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpjfm6m3_3']
[2024-07-03T23:17:57.646+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=571) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T23:17:57.673+0000] {standard_task_runner.py:63} INFO - Started process 578 to run task
[2024-07-03T23:17:57.673+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask run_script
[2024-07-03T23:17:58.273+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-04-28T00:00:00+00:00 [running]> on host 0b7358cba041
[2024-07-03T23:17:59.292+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-28T00:00:00+00:00'
[2024-07-03T23:17:59.299+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T23:17:59.317+0000] {logging_mixin.py:188} INFO - All credentials are set properly.
[2024-07-03T23:17:59.347+0000] {logging_mixin.py:188} INFO - Error al crear la tabla en Redshift: invalid literal for int() with base 10: 'None'
[2024-07-03T23:18:01.724+0000] {logging_mixin.py:188} INFO - Error al realizar la solicitud a la API: 401 Client Error: Unauthorized for url: https://api.apilayer.com/exchangerates_data/latest?symbols=EUR,USD,CNY&base=ARS
[2024-07-03T23:18:01.779+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-03T23:18:01.788+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T23:18:01.857+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-04-28T00:00:00+00:00, execution_date=20240428T000000, start_date=20240703T231757, end_date=20240703T231801
[2024-07-03T23:18:03.901+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-03T23:18:04.222+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T23:18:04.254+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
